version: '3.9'

services:
  postgresql:
    # https://hub.docker.com/_/postgres/
    container_name: postgres_container
    image: postgres:latest
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "${POSTRGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@demo.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_v_4:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - postgres

  mysql:
    # https://hub.docker.com/_/mysql
    container_name: mysql_container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_PORT: 3307
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mysql

  mysql_phpmyadmin:
    container_name: mysql_phpmyadmin_container
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    volumes:
      - phpmyadmin_v_mysql:/var/lib/pma
    restart: unless-stopped
    networks:
      - mysql

  mariadb:
    # https://hub.docker.com/_/mariadb
    container_name: mariadb_container
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      MARIADB_PORT: 3337
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mariadb

  mariadb_phpmyadmin:
    container_name: mariadb_phpmyadmin_container
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    volumes:
      - phpmyadmin_v_mariadb:/var/lib/pma
    restart: unless-stopped
    networks:
      - mariadb

volumes:
  pgadmin_v_4:
  phpmyadmin_v_mysql:
  phpmyadmin_v_mariadb:

networks:
  postgres:
    driver: bridge
  mysql:
    driver: bridge
  mariadb:
    driver: bridge
